#!/usr/bin/env python3

import os
import argparse

theme_path = os.path.expanduser("~") + "/.config/waybar/theme"

with open(theme_path, "r") as file:
    theme = file.readlines()


LightIcon = ""
DarkIcon = ""
PywalIcon = ""
WaybarIcon = ""


# Parse command-line arguments
parser = argparse.ArgumentParser(
    description="Get the state for the current theme and flush to waybar",
    formatter_class=argparse.ArgumentDefaultsHelpFormatter,
)
parser.add_argument(
    "-p",
    "--pywal",
    action="store_true",
    required=False,
    help="Export the state for the pywal icon",
)
parser.add_argument(
    "-w",
    "--waybar",
    action="store_true",
    required=False,
    help="Export the state for the waybar icon",
)
parser.add_argument(
    "-u",
    "--universal",
    action="store_true",
    required=False,
    help="Export the state for the universal mode icon",
)
args = parser.parse_args()

config = vars(args)

theme_state = dict()

for line, text in enumerate(theme):
    if "waybar" in text.lower().strip():
        if "light" in text.lower().strip():
            theme_state.update({"waybar": True})
        elif "dark" in text.lower().strip():
            theme_state.update({"waybar": False})

    elif "pywal" in text.lower().strip():
        if "light" in text.lower().strip():
            theme_state.update({"pywal": True})
        elif "dark" in text.lower().strip():
            theme_state.update({"pywal": False})

    elif "universal" in text.lower().strip():
        if "light" in text.lower().strip():
            theme_state.update({"universal": True})
        elif "dark" in text.lower().strip():
            theme_state.update({"universal": False})

    # Check arg for waybar (-w)
    if config["waybar"]:
        if "waybar=light".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{WaybarIcon}", "icon": "{WaybarIcon}", "tooltip": "Waybar light", "alt": "Waybar light", "class": "active"}}\''
            )

        elif "waybar=dark".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{WaybarIcon}", "icon": "{WaybarIcon}", "tooltip": "Waybar dark", "alt": "Waybar dark", "class": "inactive"}}\''
            )

    # Check arg for pywal (-p)
    elif config["pywal"]:
        if "pywal=light".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{PywalIcon}", "icon": "{PywalIcon}", "tooltip": "Pywal light", "alt": "Pywal light", "class": "active"}}\''
            )

        elif "pywal=dark".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{PywalIcon}", "icon": "{PywalIcon}", "tooltip": "Pywal dark", "alt": "Pywal dark", "class": "inactive"}}\''
            )

    # Check arg for universal (-u)
    elif config["universal"]:
        if "universal=light".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{LightIcon}", "icon": "{LightIcon}", "tooltip": "Light mode", "alt": "Light mode", "class": "active"}}\''
            )

        elif "universal=dark".lower().strip() in text.lower().strip():
            os.system(
                f'echo \'{{"text": "{DarkIcon}", "icon": "{DarkIcon}", "tooltip": "Dark mode", "alt": "Dark mode", "class": "inactive"}}\''
            )

if theme_state["waybar"] is True and theme_state["pywal"] is True:
    os.system(
        'sed -i "s/^universal=dark.*/universal=light/" $HOME/.config/waybar/theme'
    )
else:
    os.system(
        'sed -i "s/^universal=light.*/universal=dark/" $HOME/.config/waybar/theme'
    )
